api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: false # API is used by admin (stateful) and also by others users (stateless)
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
