vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        profile_photo:
            uri_prefix: /uploads/profiles/photos
            upload_destination: '%kernel.project_dir%/public/uploads/profiles/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
