<?php

declare(strict_types=1);

namespace App\Entity\User;

use App\Entity\CommonProperties;
use App\Repository\RequestPasswordRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: RequestPasswordRepository::class)]
class RequestPassword
{
    use CommonProperties\Required\AutoGeneratedId;

    #[ORM\Column(type: 'uuid')]
    private Uuid $token;

    #[ORM\Column]
    private \DateTimeImmutable $expireAt;

    #[ORM\ManyToOne(inversedBy: 'requestPasswords')]
    #[ORM\JoinColumn(nullable: false)]
    private User $user;

    public function __construct(int $lifetimeInSeconds)
    {
        $this->token = Uuid::v4();
        $this->expireAt = (new \DateTimeImmutable())->modify('+'.$lifetimeInSeconds.' seconds');
    }

    public function getToken(): Uuid
    {
        return $this->token;
    }

    public function setToken(Uuid $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getExpireAt(): \DateTimeImmutable
    {
        return $this->expireAt;
    }

    public function setExpireAt(\DateTimeImmutable $expireAt): self
    {
        $this->expireAt = $expireAt;

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }
}
