<?php

declare(strict_types=1);

namespace App\Entity\Page;

use App\Entity\BlameableEntity;
use App\Entity\CommonProperties;
use App\Repository\Page\PageRepository;
use App\Validator\UniqueHomepage;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: PageRepository::class)]
#[ORM\Index(columns: ['slug'])]
#[Gedmo\Loggable(logEntryClass: PageLogEntry::class)]
#[UniqueHomepage]
class Page
{
    use BlameableEntity;
    use CommonProperties\MetaRobots;
    use CommonProperties\Required\AutoGeneratedId;
    use CommonProperties\Required\Enabled;
    use CommonProperties\Required\Name;
    use CommonProperties\Seo;
    use TimestampableEntity;

    #[Gedmo\Versioned]
    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[Gedmo\Slug(fields: ['title'], updatable: false)]
    #[Gedmo\Versioned]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    /**
     * @var array<string, string>|null
     */
    #[Gedmo\Versioned]
    #[ORM\Column(nullable: true)]
    private ?array $content = null;

    #[ORM\Column(options: ['default' => false])]
    private bool $homepage = false;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): static
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return array<string, string>|null
     */
    public function getContent(): ?array
    {
        return $this->content;
    }

    public function setContent(?array $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function isHomepage(): bool
    {
        return $this->homepage;
    }

    public function setHomepage(bool $homepage): static
    {
        $this->homepage = $homepage;

        return $this;
    }
}
